---
name: Run Unit-Tests

on:
  pull_request:

jobs:
  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and install CppUTest
        run: |
          wget https://github.com/cpputest/cpputest/releases/download/v3.8/cpputest-3.8.tar.gz
          tar -xvf cpputest-3.8.tar.gz
          cd cpputest-3.8/cpputest_build
          cmake ..
          sudo make install

      - name: Build library
        run: |
          mkdir build && cd build
          cmake .. -DENABLE_COVERAGE=ON
          make

      - name: Run tests
        run: |
          ./build/tests/scheduler/test_scheduler

      - name: Install gcovr
        run: sudo apt-get install -y gcovr

      - name: Check Test Coverage
        run: |
          mkdir -p github_page/coverage
          gcovr --json-summary github_page/coverage/coverage-summary.json
          gcovr --html-details github_page/coverage/index.html

      - name: Create Coverage Badges
        uses: jaywcjlove/coverage-badges-cli@main
        with:
          style: flat
          source: github_page/coverage/coverage-summary.json
          output: github_page/coverage/badges/line_coverage.svg
          jsonPath: line_percent

      - name: Upload test coverage artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: github_page/

  deploy_to_pages:
    name: Deploy Coverage to GitHub Pages
    needs: unittest
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
